version: '3.9'

services:
  fruitvalle-app:

    build:
      context: .
      dockerfile: Dockerfile

    container_name: fruitvalle-app
    ports:
      - 4200:4200
    networks:
      - fruitvalle


networks:
  fruitvalle:
    external: true

